server:
  port: 8888

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:23306/testtest?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: testtest
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    password:
    port: 26379